export type ReadinessStatus = 'Done' | 'Needs setup' | 'Blocked' | 'Ready' | 'Connected' | 'Failed' | 'Queued';
export type ReadinessRow = { id: string; area: string; name: string; owner: string; status: ReadinessStatus; evidence: string; nextAction: string };
export type ProductionReadinessSnapshot = { connectors: ReadinessRow[]; authControls: ReadinessRow[]; auditExports: ReadinessRow[]; notificationOutbox: ReadinessRow[]; deploymentChecklist: ReadinessRow[] };
function rows(prefix: string, area: string, owner: string, names: string[]): ReadinessRow[] { return names.map((name, index) => ({ id: prefix + '-' + (index + 1), area, name, owner: index % 4 === 0 ? owner : index % 3 === 0 ? 'Platform Lead' : 'Operations Lead', status: index % 7 === 0 ? 'Blocked' : index % 5 === 0 ? 'Needs setup' : index % 3 === 0 ? 'Queued' : 'Done', evidence: name + ' evidence packet ' + (index + 1), nextAction: index % 7 === 0 ? 'Add production credentials or owner approval' : index % 5 === 0 ? 'Complete setup and rerun readiness check' : 'Monitor and keep evidence current' })); }
export const productionReadinessSnapshot: ProductionReadinessSnapshot = {
  connectors: rows('connector', 'Connectors', "Claims Legal Analytics", ["Claims Litigation Early Warning source connector 1","Claims Litigation Early Warning source connector 2","Claims Litigation Early Warning source connector 3","Claims Litigation Early Warning source connector 4","Claims Litigation Early Warning source connector 5","Claims Litigation Early Warning source connector 6","Claims Litigation Early Warning source connector 7","Claims Litigation Early Warning source connector 8","Claims Litigation Early Warning source connector 9","Claims Litigation Early Warning source connector 10","Claims Litigation Early Warning source connector 11","Claims Litigation Early Warning source connector 12","Claims Litigation Early Warning source connector 13","Claims Litigation Early Warning source connector 14","Claims Litigation Early Warning source connector 15"]),
  authControls: rows('auth', 'Enterprise Auth', 'Security Lead', ["SSO/MFA role mapping control 1","SSO/MFA role mapping control 2","SSO/MFA role mapping control 3","SSO/MFA role mapping control 4","SSO/MFA role mapping control 5","SSO/MFA role mapping control 6","SSO/MFA role mapping control 7","SSO/MFA role mapping control 8","SSO/MFA role mapping control 9","SSO/MFA role mapping control 10","SSO/MFA role mapping control 11","SSO/MFA role mapping control 12","SSO/MFA role mapping control 13","SSO/MFA role mapping control 14","SSO/MFA role mapping control 15"]),
  auditExports: rows('audit', 'Audit Exports', 'Compliance Lead', ["Claims Litigation Early Warning audit export packet 1","Claims Litigation Early Warning audit export packet 2","Claims Litigation Early Warning audit export packet 3","Claims Litigation Early Warning audit export packet 4","Claims Litigation Early Warning audit export packet 5","Claims Litigation Early Warning audit export packet 6","Claims Litigation Early Warning audit export packet 7","Claims Litigation Early Warning audit export packet 8","Claims Litigation Early Warning audit export packet 9","Claims Litigation Early Warning audit export packet 10","Claims Litigation Early Warning audit export packet 11","Claims Litigation Early Warning audit export packet 12","Claims Litigation Early Warning audit export packet 13","Claims Litigation Early Warning audit export packet 14","Claims Litigation Early Warning audit export packet 15"]),
  notificationOutbox: rows('notice', 'Notification Delivery', 'Operations Lead', ["Claims Litigation Early Warning notification delivery test 1","Claims Litigation Early Warning notification delivery test 2","Claims Litigation Early Warning notification delivery test 3","Claims Litigation Early Warning notification delivery test 4","Claims Litigation Early Warning notification delivery test 5","Claims Litigation Early Warning notification delivery test 6","Claims Litigation Early Warning notification delivery test 7","Claims Litigation Early Warning notification delivery test 8","Claims Litigation Early Warning notification delivery test 9","Claims Litigation Early Warning notification delivery test 10","Claims Litigation Early Warning notification delivery test 11","Claims Litigation Early Warning notification delivery test 12","Claims Litigation Early Warning notification delivery test 13","Claims Litigation Early Warning notification delivery test 14","Claims Litigation Early Warning notification delivery test 15"]),
  deploymentChecklist: rows('deploy', 'Deployment Checklist', 'Release Lead', ["Claims Litigation Early Warning production launch control 1","Claims Litigation Early Warning production launch control 2","Claims Litigation Early Warning production launch control 3","Claims Litigation Early Warning production launch control 4","Claims Litigation Early Warning production launch control 5","Claims Litigation Early Warning production launch control 6","Claims Litigation Early Warning production launch control 7","Claims Litigation Early Warning production launch control 8","Claims Litigation Early Warning production launch control 9","Claims Litigation Early Warning production launch control 10","Claims Litigation Early Warning production launch control 11","Claims Litigation Early Warning production launch control 12","Claims Litigation Early Warning production launch control 13","Claims Litigation Early Warning production launch control 14","Claims Litigation Early Warning production launch control 15"]),
};
